### ISSUE TITLE
图片获取问题

### ISSUE THREAD

**Issue by Cinderellar** [handsomeboyleo/Supra-Vue--#29]
您好！我学习运行了您这个项目，图片数据也都传入数据库了，但是图片一直显示不出来，方便您当时怎么解决这个问题的吗？

**Comment by handsomeboyleo** [comment]
获取图片的接口参数是什么？服务端反回了什么？最好能提供一下图片

**Comment by Cinderellar** [comment]
只有热帖页面获取不到，也没有报错，检查发现是图片地址获取错误，就在hostPost里把img :src="'http://localhost:8888'+item.img" 改为了img :src="'http://localhost:8888'+item.img_src"。
一下就好啦，嘿嘿非常感谢您还回复我，这个项目的注解也很详细，好多方法都是我没仔细了解的，我要再好好研究研究啦，非常感谢！

**Comment by handsomeboyleo** [comment]
感谢你的关注！这个项目是前年学习vue时写的demo。那时技术不是很好，很多地方都有bug是个半成品。时间太长，有问题随时交流！
